name: Main

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0']
    steps:
    # setup
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extension-csv: mbstring dom
    - name: Checkout
      uses: actions/checkout@v2

    # composer
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # tests
    - name: Run lint
      run: composer lint
    - name: Run phpunit
      run: composer run-script test
    - name: Run stan
      run: composer run-script stan
